### ISSUE TITLE
Detailed calculation methods for pitch and speaking speed

### ISSUE THREAD

**Issue by hoang1007** [line/LibriTTS-P#3]
Hello @MasayaKawamura

Thank you for the LibriTTS-P dataset release and paper. I am using your dataset to training my model. Can you please provide detailed method to calculate pitch and speaking speed for each utterance in the dataset? 

Thanks!

**Comment by r9y9** [comment]
Hi, sorry for being late. We've open-sourced our code for PromptTTS++ with the full details of style prompt generation. Please check https://github.com/line/promptttspp/tree/main/data_prep for details.  For instance, https://github.com/line/promptttspp/blob/3e6bd0eaa7d0bfadb5f33a530726dd78efc748dd/data_prep/compute_utt_stats.py#L32-L61 is the code to compute speaking speed.
